### ISSUE TITLE
[Translate] Allow Markdown

### ISSUE THREAD

**Issue by Henry-Hiles** [TymanWasTaken/aliucord-plugins#15] opened 2022-02-01 18:04 UTC
Right now text inside spoilers, or with emoji don't get translated, it would be greatly appreciated if this could be fixed. Thank you.

**Comment by TymanWasTaken** [comment] 2022-07-14 15:14
Ill fix this in a bit, but this is also a duplicate of #6 anyway

**Closed by TymanWasTaken** 2022-07-14 15:14 UTC
