### ISSUE TITLE
[Translate plugin with MessageLogger plugin installed and activated] The fix don't working

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [TymanWasTaken/aliucord-plugins#20] opened 2022-07-26 13:24 UTC
Hi developers,

Today I have bad news about those plugins. I have the problem to translate messages in locked channels, to translate channels by webhook and bots/system bots and to translate normal messages via Translate Plugin without MessageLogger. I tried with MessageLogger but nothing is fixed, only normal messages from normal not-locked channels is working in translating the messages.

This is the log I got from this problem so I hope this can help.

![Screenshot-1.jpg](https://user-images.githubusercontent.com/45666011/181016421-96cab28c-d426-4201-ac57-e985cb2cfc19.jpg)
![Screenshot-2.jpg](https://user-images.githubusercontent.com/45666011/181016456-5cf2701d-5b0a-496f-90ab-d13755caf195.jpg)

Happy work and have a nice day/night!

- Best regards
   The Aliucord user

**Comment by TymanWasTaken** [comment] 2023-01-02 06:27
Duplicate of #6

**Closed by TymanWasTaken** 2023-01-02 06:27 UTC
